import 'models/Dog.dart';
import 'models/Owner.dart';

final Owner owner = Owner("Spikey Sanju", "Developer & Pet Lover", "assets/owner.jpg");
final List<Dog> dogList = [
  Dog(
    0,
    "Hachiko",
    3.5,
    "Male",
    "Brown",
    12.9,
    "389m away",
    "assets/orange_dog.png",
    "A friendly and loyal dog looking for a loving home.",
    owner,
    "Playful",
  ),
  Dog(
    1,
    "Skooby Doo",
    3.5,
    "Male",
    "Gold",
    12.4,
    "412m away",
    "assets/blue_dog.png",
    "An adventurous dog who loves to solve mysteries.",
    owner,
    "Adventurous",
  ),
  Dog(
    2,
    "Miss Agnes",
    3.5,
    "Female",
    "White",
    9.6,
    "879m away",
    "assets/red_dog.png",
    "A gentle and caring dog with a big heart.",
    owner,
    "Gentle",
  ),
  Dog(
    3,
    "Cyrus",
    3.5,
    "Male",
    "Black",
    8.2,
    "672m away",
    "assets/yellow_dog.png",
    "A strong and protective companion.",
    owner,
    "Protective",
  ),
  Dog(
    4,
    "Shelby",
    3.5,
    "Female",
    "Chocolate",
    14.9,
    "982m away",
    "assets/white_dog.png",
    "A playful and energetic dog ready to brighten your day.",
    owner,
    "Energetic",
  ),
];

